### ISSUE TITLE
Integrating with X86 and Gem5

### ISSUE THREAD

**Issue by gr-rahimi** [estwings57/CasHMC#1]
Hi,

I want to use this simulator for X86 ISA with GEM5. The script you have provided for integrating with Gem5, uses ARM by default. Is it possible to use it with X86 too?

Thanks,
Reza

**Comment by estwings57** [comment]
Thank you for having a interest in CasHMC simulator.
Of course, CasHMC can be intergrated with all ISAs in gem5.
If you already integrated CasHMC to gem5 by intergrating script file [[CasHMC/integration/gem5/integ_CasHMC-gem5.sh],](https://github.com/estwings57/CasHMC/blob/v-1/integration/gem5/integ_CasHMC-gem5.sh)
you can build whatever you want to, as like below
`scons build/$ISA/gem5.opt`

For example - X86 ISA
`scons build/X86/gem5.opt`
`build/X86/gem5.opt --outdir=./result ./configs/example/se.py --cpu-type=DerivO3CPU --caches --mem-type=DRAMSim2 -c ./tests/test-progs/hello/bin/x86/linux/hello`

Please refer to [README file](https://github.com/estwings57/CasHMC/blob/v-1/README) about integration with gem5 simulator.

Thanks,
Dong-Ik Jeon

**Comment by gr-rahimi** [comment]
Thanks. It worked.
