### ISSUE TITLE
base/misc.hh: No such file or directory

### ISSUE THREAD

**Issue by warsier** [estwings57/CasHMC#2]
Hi, I pulled the latest version of gem5 and tried to execute your script on it, but got the following error when compiling.
`build/X86/mem/dramsim2_wrapper.cc:47:24: fatal error: base/misc.hh: No such file or directory`
I think they addressed similar issue in [http://repo.gem5.org/gem5/rev/a3c5434d3c4f](http://repo.gem5.org/gem5/rev/a3c5434d3c4f).
The error was due to a filename modification.

**Comment by estwings57** [comment]
I'm sorry for late reply.
As your comment, 'base/misc.hh' is changed to 'base/logging.hh' in latest version of gem5.
I updated the modified script file.
Thank you for letting me know.

**Comment by warsier** [comment]
Thank you for the reply.
